version: '3'

services:
  telegram-bot:
    build: .
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb+srv://azharsayzz:Azhar@70@cluster0.0encvzq.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    restart: unless-stopped 