services:
  # A Docker web service
  - type: web
    name: telegram-storage-bot
    env: docker
    plan: free
    # Add persistent disk to store bot data
    disk:
      name: bot-data
      mountPath: /app/data
      sizeGB: 1
    # Health check to ensure the service is running
    healthCheckPath: /health
    healthCheckTimeout: 5
    # Configure ports
    envVars:
      - key: PORT
        value: 10000
      - key: HEALTH_PORT
        value: 8080
      # RENDER will be set to true automatically
      - key: RENDER
        value: true
    # Auto-deploy on changes to main branch
    autoDeploy: true
    # Uncomment these and add your values if you want to store in render.yaml
    # It's recommended to use the Render dashboard for sensitive values
    # envVars:
    #   - key: BOT_TOKEN
    #     value: your_token_here
    #   - key: CHANNEL_ID
    #     value: your_channel_id
    #   - key: CHANNEL_FIRST_MESSAGE_ID
    #     value: 2 